name: build-release-actions-workflow
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - '*' # Push events to matching v*, i.e. v1.0, v20.15.10

permissions:
    contents: write

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
          
      - shell: cmd
        run: |
          docker-compose --file docker-compose.yml up --build && docker-compose --file docker-compose.yml down
